function inputs = inputDialog(dialog)
% inputDialog Function
%
% The 'inputDialog' function collects user inputs needed for configuring 
% a multi-observer system. It displays a dialog box prompting for key 
% parameters or uses predefined default inputs if the dialog is disabled.
%
% Documentation written by ChatGPT.
%
% Syntax:
% -------
% inputs = inputDialog(dialog)
%
% Inputs:
% -------
% - 'dialog': A logical value:
%     - 'true': Displays an input dialog box for the user to input values.
%     - 'false': Returns predefined default inputs without showing the dialog box.
%
% Outputs:
% --------
% - 'inputs': A cell array containing user-provided or default input values.
%
%
% Example:
% --------
% Using the dialog:
% inputs = inputDialog(true);
% Prompts the user for inputs using an input dialog box.
%
% Using default inputs:
% inputs = inputDialog(false);
% Returns:
% inputs = {'2', '5', '3', '2 5', '3', '1', '0 5', ...
%           '0.3 -0.1 0.5 0.2 -0.4 0.6 0.3 0.3 -0.7 0.4 -0.2 0.6', ...
%           '0 1 0', '1', 'loose', '0'};
    
    % Input dialog box
    inputPrompt = {'System selection (number indicates amount of mass-spring-dampers in series)',...
        'Number of system outputs',...
        'M, number of attacked outputs (max: largest integer M so that 2M<N holds)',...
        'Attacked outputs (empty string will attack random outputs)',...
        'Size of each J-observer (max: N-M)',...
        'Size of each P-observer (max: N-2M)',...
        'Timespan (enter tmin and tmax separtated by spaces)',...
        'x0 (enter x0 seperated by spaces)',...
        'CMO2D CMO3D SSMO',...
        'Linear (1) or Nonlinear (0) model',...
        'loose or strict aggregate sensors',...
        'Noise variance (generated with randn)'};
    
    % Prefilled inputs
    definputs = {'2',...
        '5',...
        '3',...
        '2 5',...
        '3',...
        '1',...
        '0 5',...
        '0.3 -0.1 0.5 0.2 -0.4 0.6 0.3 0.3 -0.7 0.4 -0.2 0.6',...
        '0 1 0',...
        '1',...
        'loose',...
        '0'};
    
    % Check if input is required, ohterwise use prefilled inputs
    if dialog
        inputs = inputdlg(inputPrompt,'CMO inputs',[1 40],definputs);
    else
        inputs = definputs;
    end
end